activities = [
  "Read a chapter of a book",
  "Go for a 15-minute walk (repeatable)",
  "Call or text a friend/family member",
  "Try a new recipe for a meal or snack",
  "Drink a glass of water (repeatable)",
  "Do 20 minutes of exercise",
  "Meditate for 5-10 minutes (repeatable)",
  "Learn a new word and its definition",
  "Watch an educational video/documentary short",
  "Listen to a new podcast episode",
  "Write a short journal entry (repeatable)",
  "Tidy up one area/room for 10 minutes",
  "Organize a drawer or shelf",
  "Water your plants (repeatable)",
  "Do 5 minutes of stretching (repeatable)",
  "Work on a puzzle (jigsaw, crossword, Sudoku)",
  "Play a quick card game or board game",
  "Spend 15 minutes learning a new skill online",
  "Look at art online or visit a virtual museum tour",
  "Take an interesting photo",
  "Do a small act of kindness for someone",
  "Give a genuine compliment to someone",
  "Spend 30 minutes screen-free (no phone/computer/TV)",
  "Plan your tasks for tomorrow",
  "Listen to a new music genre or artist (repeatable)",
  "Engage in a creative hobby (draw, write, craft) (repeatable)",
  "Bake cookies or a simple treat",
  "Step outside and observe the sky (clouds/stars) (repeatable)",
  "Identify 3 things you are grateful for today (repeatable)",
  "Declutter your email inbox"
]